apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: be-ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: republikorp.local
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: be-svc
                port:
                  number: 3333
          - path: /dav
            pathType: Prefix
            backend:
              service:
                name: be-svc
                port:
                  number: 2100
