apiVersion: v1
kind: Secret
metadata:
  name: be-env-secret
  namespace: backend
type: Opaque
data:
  APP_KEY: "pWfDjtvjhlHD3NshauMIkWkd8LQLXuUd"
  PG_PASSWORD: "-^#m4rTa8aK*T3l0r#-^"
  JWT_SECRET: "pWfDjtvjhlHD3NshauMIkWkd8LQLXuUd"
  MINIO_ACCESS_KEY: "DvEBBPD6YCHjrfKwHHjz"
  MINIO_SECRET_KEY: "Nc8daWiXmVpkG3K1J8iQyGozjzHlijqJX50znPNF"
  ONLYOFFICE_JWT_SECRET: "NLPVHfka2359rbEKetfz1YrpgFm81Ian"
  EJABBERD_ADMIN_USER: isan@santuy.info
  EJABBERD_ADMIN_PASS: isan123
  ONESIGNAL_APP_ID: "6ca282b3-137e-470f-b7b5-e98afd7b9951"
  ONESIGNAL_REST_API_KEY: "os_v2_app_nsrifmytpzdq7n5v5gfp264zkhhxvmtxjodestmllamttisvasvehs7vmjolcgqlfjg6gneejosf6ogrb3ebox4mxpnu2zwig7nohdy"
