apiVersion: v1
kind: Secret
metadata:
  name: fe-env-secret
  namespace: frontend
data:
  SESSION_SECRET: uXbvFFp1wPirP7X04rngGDGGV8wyRdRzKxkZ3kPFmh0=
  ALTCHA_HMAC_KEY: asdjkfh2387ryhfsdf7823y4rhwefushdf7823y4
